version: '3.8'
services:
  dataretrieval:
    build:
      context: .
      dockerfile: ./dataretrieval/Dockerfile
    command: 'python ./dataretrieval/main.py'
    environment:
      - isDocker=true
    ports:
      - 5002:5002
    volumes:
      - .:/dataretrieval