version: '3.8'
services:
  dataretrieval:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      - isDocker=true
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DB=metricsDb
    ports:
      - 5002:5002
    volumes:
      - .:/dataretrieval