version: '3.8'
services:
  etldatapipeline:
    build:
      context: .
      dockerfile: ./etldatapipeline/Dockerfile
    command: 'python ./etldatapipeline/main.py'
    ports:
      - 5000:5000
    volumes:
      - .:/etldatapipeline
  datastorage:
    build:
      context: .
      dockerfile: ./datastorage/Dockerfile
    command: 'python ./datastorage/main.py'
    ports:
      - 5001:5000
    volumes:
      - .:/datastorage
  dataretrieval:
    build:
      context: .
      dockerfile: ./dataretrieval/Dockerfile
    command: 'python ./dataretrieval/main.py'
    ports:
      - 5002:5000
    volumes:
      - .:/dataretrieval

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./etldatapipeline/prometheus.yml:/etc/prometheus/prometheus.yml