version: '3.8'
services:
  datastorage:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 5001:5001
    networks:
      - dsbd_microservices_default
    volumes:
      - .:/datastorage
    environment:
      - isDocker=true
networks:
  dsbd_microservices_default:
    external: true