version: '3.8'
services:
  datastorage:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 5001:5001
    networks:
      - dsbd_metricshub_default
    volumes:
      - .:/datastorage
    environment:
      - isDocker=true
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DB=metricsDb
networks:
  dsbd_metricshub_default:
    external: true