version: '3.8'
services:
  etldatapipeline:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      - isDocker=true
    ports:
      - 5000:5000
    volumes:
      - .:/etldatapipeline