version: '3.8'
services:
  etldatapipeline:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      - isDocker=true
    networks:
      - dsbd_metricshub_default
    ports:
      - 5000:5000
    volumes:
      - .:/etldatapipeline
networks:
  dsbd_metricshub_default:
    external: true